name: cricket-fitness-api
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ip6net

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: cricket_fitness_api
    volumes:
      - ./:/app
      - web_venv:/app/.venv
    ports:
      - "8020:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ip6net

volumes:
  postgres_data:
  web_venv:

networks:
  ip6net:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: "2001:db8::/64"
