"""Added fitness tables and cricket tables

Revision ID: 35ac3df3fb39
Revises: 70a4bc3c6930
Create Date: 2025-07-19 09:17:51.486099

"""

from typing import Sequence, Union

import sqlalchemy as sa

import common.mixins.timestamp_mixin
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35ac3df3fb39"
down_revision: Union[str, Sequence[str], None] = "70a4bc3c6930"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cricket_coaching_entries",
        sa.Column(
            "entry_type",
            sa.Enum("FITNESS", "CRICKET_COACHING", "CRICKET_MATCH", "REST_DAY", name="entrytype"),
            nullable=False,
        ),
        sa.Column("coach_name", sa.String(), nullable=False),
        sa.Column("session_type", sa.String(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "primary_focus",
            sa.Enum(
                "TECHNIQUE",
                "FITNESS",
                "TACTICS",
                "MENTAL",
                "SPECIFIC_SKILLS",
                "GAME_SITUATION",
                name="coachingfocus",
            ),
            nullable=True,
        ),
        sa.Column(
            "secondary_focus",
            sa.Enum(
                "TECHNIQUE",
                "FITNESS",
                "TACTICS",
                "MENTAL",
                "SPECIFIC_SKILLS",
                "GAME_SITUATION",
                name="coachingfocus",
            ),
            nullable=True,
        ),
        sa.Column("skills_practiced", sa.JSON(), nullable=False),
        sa.Column(
            "discipline_focus",
            sa.Enum(
                "BATTING",
                "BOWLING",
                "FIELDING",
                "WICKET_KEEPING",
                "ALL_ROUND",
                name="cricketdiscipline",
            ),
            nullable=True,
        ),
        sa.Column("warm_up_minutes", sa.Integer(), nullable=True),
        sa.Column("skill_work_minutes", sa.Integer(), nullable=True),
        sa.Column("game_simulation_minutes", sa.Integer(), nullable=True),
        sa.Column("cool_down_minutes", sa.Integer(), nullable=True),
        sa.Column("equipment_used", sa.JSON(), nullable=True),
        sa.Column("facility_name", sa.String(), nullable=True),
        sa.Column("indoor_outdoor", sa.String(), nullable=True),
        sa.Column("technique_rating", sa.Integer(), nullable=True),
        sa.Column("effort_level", sa.Integer(), nullable=True),
        sa.Column("coach_feedback", sa.String(), nullable=True),
        sa.Column("improvement_areas", sa.JSON(), nullable=True),
        sa.Column("session_goals", sa.JSON(), nullable=True),
        sa.Column("goals_achieved", sa.JSON(), nullable=True),
        sa.Column("next_session_focus", sa.String(), nullable=True),
        sa.Column("session_cost", sa.Float(), nullable=True),
        sa.Column("group_size", sa.Integer(), nullable=True),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("original_transcript", sa.String(), nullable=False),
        sa.Column("overall_confidence_score", sa.Float(), nullable=False),
        sa.Column("processing_duration", sa.Float(), nullable=True),
        sa.Column("data_quality_score", sa.Float(), nullable=True),
        sa.Column("manual_overrides", sa.JSON(), nullable=True),
        sa.Column("validation_notes", sa.String(), nullable=True),
        sa.Column("mental_state", sa.String(), nullable=False),
        sa.Column("energy_level", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("activity_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Unique identifier for the record (Primary Key).",
        ),
        sa.Column(
            "created_at",
            common.mixins.timestamp_mixin.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record creation timestamp.",
        ),
        sa.Column(
            "updated_at",
            common.mixins.timestamp_mixin.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record last update timestamp.",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_cricket_coaching_entries_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_cricket_coaching_entries_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cricket_coaching_entries_conversation_id"),
        "cricket_coaching_entries",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cricket_coaching_entries_entry_type"),
        "cricket_coaching_entries",
        ["entry_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cricket_coaching_entries_id"), "cricket_coaching_entries", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_cricket_coaching_entries_session_id"),
        "cricket_coaching_entries",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cricket_coaching_entries_user_id"),
        "cricket_coaching_entries",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "cricket_match_entries",
        sa.Column(
            "entry_type",
            sa.Enum("FITNESS", "CRICKET_COACHING", "CRICKET_MATCH", "REST_DAY", name="entrytype"),
            nullable=False,
        ),
        sa.Column(
            "match_format",
            sa.Enum(
                "T20",
                "ODI",
                "TEST",
                "LIST_A",
                "FIRST_CLASS",
                "FRIENDLY",
                "PRACTICE_MATCH",
                name="matchformat",
            ),
            nullable=True,
        ),
        sa.Column("opposition_team", sa.String(), nullable=False),
        sa.Column("venue", sa.String(), nullable=False),
        sa.Column("home_away", sa.String(), nullable=False),
        sa.Column("result", sa.String(), nullable=False),
        sa.Column("team_name", sa.String(), nullable=False),
        sa.Column("team_total", sa.Integer(), nullable=True),
        sa.Column("team_wickets", sa.Integer(), nullable=True),
        sa.Column("team_overs", sa.Float(), nullable=True),
        sa.Column("opposition_total", sa.Integer(), nullable=True),
        sa.Column("opposition_wickets", sa.Integer(), nullable=True),
        sa.Column("opposition_overs", sa.Float(), nullable=True),
        sa.Column("batting_position", sa.Integer(), nullable=True),
        sa.Column("runs_scored", sa.Integer(), nullable=True),
        sa.Column("balls_faced", sa.Integer(), nullable=True),
        sa.Column("boundaries", sa.Integer(), nullable=True),
        sa.Column("sixes", sa.Integer(), nullable=True),
        sa.Column("dismissal_type", sa.String(), nullable=True),
        sa.Column("strike_rate", sa.Float(), nullable=True),
        sa.Column("overs_bowled", sa.Float(), nullable=True),
        sa.Column("runs_conceded", sa.Integer(), nullable=True),
        sa.Column("wickets_taken", sa.Integer(), nullable=True),
        sa.Column("economy_rate", sa.Float(), nullable=True),
        sa.Column("best_bowling", sa.String(), nullable=True),
        sa.Column("catches_taken", sa.Integer(), nullable=True),
        sa.Column("run_outs", sa.Integer(), nullable=True),
        sa.Column("stumpings", sa.Integer(), nullable=True),
        sa.Column("fielding_position", sa.String(), nullable=True),
        sa.Column("weather_conditions", sa.String(), nullable=True),
        sa.Column("pitch_conditions", sa.String(), nullable=True),
        sa.Column("toss_won_by", sa.String(), nullable=True),
        sa.Column("elected_to", sa.String(), nullable=True),
        sa.Column("batting_performance", sa.Integer(), nullable=True),
        sa.Column("bowling_performance", sa.Integer(), nullable=True),
        sa.Column("fielding_performance", sa.Integer(), nullable=True),
        sa.Column("overall_performance", sa.Integer(), nullable=True),
        sa.Column("key_moments", sa.JSON(), nullable=True),
        sa.Column("what_went_well", sa.JSON(), nullable=True),
        sa.Column("areas_for_improvement", sa.JSON(), nullable=True),
        sa.Column("captain_feedback", sa.String(), nullable=True),
        sa.Column("coach_feedback", sa.String(), nullable=True),
        sa.Column("match_duration_hours", sa.Float(), nullable=True),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("match_fee", sa.Float(), nullable=True),
        sa.Column("travel_distance_km", sa.Float(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("original_transcript", sa.String(), nullable=False),
        sa.Column("overall_confidence_score", sa.Float(), nullable=False),
        sa.Column("processing_duration", sa.Float(), nullable=True),
        sa.Column("data_quality_score", sa.Float(), nullable=True),
        sa.Column("manual_overrides", sa.JSON(), nullable=True),
        sa.Column("validation_notes", sa.String(), nullable=True),
        sa.Column("mental_state", sa.String(), nullable=False),
        sa.Column("energy_level", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("activity_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Unique identifier for the record (Primary Key).",
        ),
        sa.Column(
            "created_at",
            common.mixins.timestamp_mixin.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record creation timestamp.",
        ),
        sa.Column(
            "updated_at",
            common.mixins.timestamp_mixin.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record last update timestamp.",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_cricket_match_entries_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_cricket_match_entries_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cricket_match_entries_conversation_id"),
        "cricket_match_entries",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cricket_match_entries_entry_type"),
        "cricket_match_entries",
        ["entry_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cricket_match_entries_id"), "cricket_match_entries", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_cricket_match_entries_session_id"),
        "cricket_match_entries",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cricket_match_entries_user_id"), "cricket_match_entries", ["user_id"], unique=False
    )
    op.create_table(
        "fitness_entries",
        sa.Column(
            "entry_type",
            sa.Enum("FITNESS", "CRICKET_COACHING", "CRICKET_MATCH", "REST_DAY", name="entrytype"),
            nullable=False,
        ),
        sa.Column(
            "exercise_type",
            sa.Enum("CARDIO", "STRENGTH", "FLEXIBILITY", "SPORTS", "OTHER", name="exercisetype"),
            nullable=False,
        ),
        sa.Column("exercise_name", sa.String(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "intensity",
            sa.Enum("LOW", "MODERATE", "HIGH", "VERY_HIGH", name="intensitylevel"),
            nullable=False,
        ),
        sa.Column("calories_burned", sa.Integer(), nullable=True),
        sa.Column("distance_km", sa.Float(), nullable=True),
        sa.Column("sets", sa.Integer(), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("heart_rate_avg", sa.Integer(), nullable=True),
        sa.Column("heart_rate_max", sa.Integer(), nullable=True),
        sa.Column("workout_rating", sa.Integer(), nullable=True),
        sa.Column("equipment_used", sa.JSON(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("gym_name", sa.String(), nullable=True),
        sa.Column("weather_conditions", sa.String(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("workout_partner", sa.String(), nullable=True),
        sa.Column("trainer_name", sa.String(), nullable=True),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("original_transcript", sa.String(), nullable=False),
        sa.Column("overall_confidence_score", sa.Float(), nullable=False),
        sa.Column("processing_duration", sa.Float(), nullable=True),
        sa.Column("data_quality_score", sa.Float(), nullable=True),
        sa.Column("manual_overrides", sa.JSON(), nullable=True),
        sa.Column("validation_notes", sa.String(), nullable=True),
        sa.Column("mental_state", sa.String(), nullable=False),
        sa.Column("energy_level", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("activity_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Unique identifier for the record (Primary Key).",
        ),
        sa.Column(
            "created_at",
            common.mixins.timestamp_mixin.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record creation timestamp.",
        ),
        sa.Column(
            "updated_at",
            common.mixins.timestamp_mixin.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record last update timestamp.",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_fitness_entries_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_fitness_entries_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fitness_entries_conversation_id"),
        "fitness_entries",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fitness_entries_entry_type"), "fitness_entries", ["entry_type"], unique=False
    )
    op.create_index(op.f("ix_fitness_entries_id"), "fitness_entries", ["id"], unique=True)
    op.create_index(
        op.f("ix_fitness_entries_session_id"), "fitness_entries", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_fitness_entries_user_id"), "fitness_entries", ["user_id"], unique=False
    )
    op.create_table(
        "rest_day_entries",
        sa.Column(
            "entry_type",
            sa.Enum("FITNESS", "CRICKET_COACHING", "CRICKET_MATCH", "REST_DAY", name="entrytype"),
            nullable=False,
        ),
        sa.Column("rest_type", sa.String(), nullable=False),
        sa.Column("planned", sa.Boolean(), nullable=False),
        sa.Column("recovery_activities", sa.JSON(), nullable=True),
        sa.Column("sleep_hours", sa.Float(), nullable=True),
        sa.Column("sleep_quality", sa.Integer(), nullable=True),
        sa.Column("muscle_soreness", sa.Integer(), nullable=True),
        sa.Column("fatigue_level", sa.Integer(), nullable=True),
        sa.Column("stress_level", sa.Integer(), nullable=True),
        sa.Column("recovery_score", sa.Integer(), nullable=True),
        sa.Column("readiness_for_next_workout", sa.Integer(), nullable=True),
        sa.Column("meditation_minutes", sa.Integer(), nullable=True),
        sa.Column("stretching_minutes", sa.Integer(), nullable=True),
        sa.Column("massage_minutes", sa.Integer(), nullable=True),
        sa.Column("hydration_liters", sa.Float(), nullable=True),
        sa.Column("protein_focus", sa.Boolean(), nullable=True),
        sa.Column("nutrition_notes", sa.String(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("original_transcript", sa.String(), nullable=False),
        sa.Column("overall_confidence_score", sa.Float(), nullable=False),
        sa.Column("processing_duration", sa.Float(), nullable=True),
        sa.Column("data_quality_score", sa.Float(), nullable=True),
        sa.Column("manual_overrides", sa.JSON(), nullable=True),
        sa.Column("validation_notes", sa.String(), nullable=True),
        sa.Column("mental_state", sa.String(), nullable=False),
        sa.Column("energy_level", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("activity_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Unique identifier for the record (Primary Key).",
        ),
        sa.Column(
            "created_at",
            common.mixins.timestamp_mixin.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record creation timestamp.",
        ),
        sa.Column(
            "updated_at",
            common.mixins.timestamp_mixin.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record last update timestamp.",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_rest_day_entries_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_rest_day_entries_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rest_day_entries_conversation_id"),
        "rest_day_entries",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rest_day_entries_entry_type"), "rest_day_entries", ["entry_type"], unique=False
    )
    op.create_index(op.f("ix_rest_day_entries_id"), "rest_day_entries", ["id"], unique=True)
    op.create_index(
        op.f("ix_rest_day_entries_session_id"), "rest_day_entries", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_rest_day_entries_user_id"), "rest_day_entries", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rest_day_entries_user_id"), table_name="rest_day_entries")
    op.drop_index(op.f("ix_rest_day_entries_session_id"), table_name="rest_day_entries")
    op.drop_index(op.f("ix_rest_day_entries_id"), table_name="rest_day_entries")
    op.drop_index(op.f("ix_rest_day_entries_entry_type"), table_name="rest_day_entries")
    op.drop_index(op.f("ix_rest_day_entries_conversation_id"), table_name="rest_day_entries")
    op.drop_table("rest_day_entries")
    op.drop_index(op.f("ix_fitness_entries_user_id"), table_name="fitness_entries")
    op.drop_index(op.f("ix_fitness_entries_session_id"), table_name="fitness_entries")
    op.drop_index(op.f("ix_fitness_entries_id"), table_name="fitness_entries")
    op.drop_index(op.f("ix_fitness_entries_entry_type"), table_name="fitness_entries")
    op.drop_index(op.f("ix_fitness_entries_conversation_id"), table_name="fitness_entries")
    op.drop_table("fitness_entries")
    op.drop_index(op.f("ix_cricket_match_entries_user_id"), table_name="cricket_match_entries")
    op.drop_index(op.f("ix_cricket_match_entries_session_id"), table_name="cricket_match_entries")
    op.drop_index(op.f("ix_cricket_match_entries_id"), table_name="cricket_match_entries")
    op.drop_index(op.f("ix_cricket_match_entries_entry_type"), table_name="cricket_match_entries")
    op.drop_index(
        op.f("ix_cricket_match_entries_conversation_id"), table_name="cricket_match_entries"
    )
    op.drop_table("cricket_match_entries")
    op.drop_index(
        op.f("ix_cricket_coaching_entries_user_id"), table_name="cricket_coaching_entries"
    )
    op.drop_index(
        op.f("ix_cricket_coaching_entries_session_id"), table_name="cricket_coaching_entries"
    )
    op.drop_index(op.f("ix_cricket_coaching_entries_id"), table_name="cricket_coaching_entries")
    op.drop_index(
        op.f("ix_cricket_coaching_entries_entry_type"), table_name="cricket_coaching_entries"
    )
    op.drop_index(
        op.f("ix_cricket_coaching_entries_conversation_id"), table_name="cricket_coaching_entries"
    )
    op.drop_table("cricket_coaching_entries")
    # ### end Alembic commands ###
