"""Add user and user identity tables

Revision ID: abe7610f7ee7
Revises:
Create Date: 2025-07-16 10:44:40.850175

"""

from collections.abc import Sequence

import sqlalchemy as sa

import common
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abe7610f7ee7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("first_name", sa.String(length=32), nullable=True, comment="User's first name"),
        sa.Column("last_name", sa.String(length=32), nullable=True, comment="User's last name"),
        sa.Column(
            "phone_number",
            sa.String(length=20),
            nullable=True,
            comment="User's phone number",
        ),
        sa.Column("email", sa.String(length=256), nullable=True, comment="User's email address"),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Unique identifier for the record (Primary Key).",
        ),
        sa.Column(
            "created_at",
            common.mixins.timestamp_mixin.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record creation timestamp.",
        ),
        sa.Column(
            "updated_at",
            common.mixins.timestamp_mixin.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record last update timestamp.",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    op.create_index(op.f("ix_users_phone_number"), "users", ["phone_number"], unique=True)
    op.create_table(
        "user_identities",
        sa.Column("provider_user_id", sa.String(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("SUPABASE", "FIREBASE", name="identityprovider"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Unique identifier for the record (Primary Key).",
        ),
        sa.Column(
            "created_at",
            common.mixins.timestamp_mixin.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record creation timestamp.",
        ),
        sa.Column(
            "updated_at",
            common.mixins.timestamp_mixin.UTCDateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Record last update timestamp.",
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_identities_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_identities_id"), "user_identities", ["id"], unique=True)
    op.create_index(
        op.f("ix_user_identities_provider_user_id"),
        "user_identities",
        ["provider_user_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_user_identities_user_id"),
        "user_identities",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_identities_user_id"), table_name="user_identities")
    op.drop_index(op.f("ix_user_identities_provider_user_id"), table_name="user_identities")
    op.drop_index(op.f("ix_user_identities_id"), table_name="user_identities")
    op.drop_table("user_identities")
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
