name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check Out the Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set Up QEMU for Multi-Platform Builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Step 3: Set Up Docker Buildx
        # Enables building multi-platform Docker images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          # Use the service account key stored as a GitHub Secret
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      # Step 5: Set Up gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: blinticai   # Replace with your GCP project ID

      # Step 6: Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-west2-docker.pkg.dev --quiet

      # Step 7: Build and Push Docker Image
      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag us-west2-docker.pkg.dev/blinticai/blinticai/sports-analysis:${{ github.sha }} \
            --tag us-west2-docker.pkg.dev/blinticai/blinticai/sports-analysis:latest \
            -f Dockerfile.prod \
            --push .

      # Step 8: Deploy to Cloud Run using Secrets from Secret Manager
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy sports-analysis \
            --image us-west2-docker.pkg.dev/blinticai/blinticai/sports-analysis:latest \
            --platform managed \
            --region us-west2 \
            --allow-unauthenticated \
            --clear-env-vars \
            --set-secrets="APP_API_TITLE=APP_API_TITLE:latest,\
            APP_API_DESCRIPTION=APP_API_DESCRIPTION:latest,\
            APP_API_VERSION=APP_API_VERSION:latest,\
            APP_CONTACT_NAME=APP_CONTACT_NAME:latest,\
            APP_CONTACT_URL=APP_CONTACT_URL:latest,\
            APP_CONTACT_EMAIL=APP_CONTACT_EMAIL:latest,\
            APP_DOCS_URL=APP_DOCS_URL:latest,\
            APP_REDOC_URL=APP_REDOC_URL:latest,\
            APP_OPENAPI_URL=APP_OPENAPI_URL:latest,\
            APP_SERVER_HOST=APP_SERVER_HOST:latest,\
            APP_SERVER_PORT=APP_SERVER_PORT:latest,\
            APP_SERVER_DEBUG=APP_SERVER_DEBUG:latest,\
            APP_LOG_LEVEL=APP_LOG_LEVEL:latest,\
            APP_CORS_ALLOW_ORIGINS=APP_CORS_ALLOW_ORIGINS:latest,\
            APP_CORS_ALLOW_CREDENTIALS=APP_CORS_ALLOW_CREDENTIALS:latest,\
            APP_CORS_ALLOW_METHODS=APP_CORS_ALLOW_METHODS:latest,\
            APP_CORS_ALLOW_HEADERS=APP_CORS_ALLOW_HEADERS:latest,\
            APP_SUPABASE_URL=APP_SUPABASE_URL:latest,\
            APP_SUPABASE_JWT_SECRET=APP_SUPABASE_JWT_SECRET:latest,\
            APP_SUPABASE_KEY=APP_SUPABASE_KEY:latest,\
            APP_SUPABASE_S3_URL=APP_SUPABASE_S3_URL:latest,\
            APP_SUPABASE_REGION=APP_SUPABASE_REGION:latest,\
            APP_SUPABSE_ACCESS_KEY_ID=APP_SUPABSE_ACCESS_KEY_ID:latest,\
            APP_SUPABASE_SECRET_ACCESS_KEY=APP_SUPABASE_SECRET_ACCESS_KEY:latest,\
            APP_DB_HOST=APP_DB_HOST:latest,\
            APP_DB_PORT=APP_DB_PORT:latest,\
            APP_DB_USER=APP_DB_USER:latest,\
            APP_DB_PASSWORD=APP_DB_PASSWORD:latest,\
            APP_DB_NAME=APP_DB_NAME:latest,\
            APP_EMBEDDING_PROVIDER=APP_EMBEDDING_PROVIDER:latest,\
            APP_EMBEDDING_MODEL=APP_EMBEDDING_MODEL:latest,\
            APP_EMBEDDING_EMBEDDING_DIM=APP_EMBEDDING_EMBEDDING_DIM:latest,\
            APP_EMBEDDING_DISTANCE_METRIC=APP_EMBEDDING_DISTANCE_METRIC:latest,\
            APP_VECTOR_STORAGE_PROVIDER=APP_VECTOR_STORAGE_PROVIDER:latest,\
            APP_FILE_STORAGE_TYPE=APP_FILE_STORAGE_TYPE:latest,\
            APP_FILE_STORAGE_BUCKET=APP_FILE_STORAGE_BUCKET:latest,\
            FILE_STORAGE_REGION=FILE_STORAGE_REGION:latest,\
            FILE_STORAGE_ENDPOINT=FILE_STORAGE_ENDPOINT:latest,\
            FILE_STORAGE_CREDS_ACCESS_KEY_ID=FILE_STORAGE_CREDS_ACCESS_KEY_ID:latest,\
            FILE_STORAGE_CREDS_SECRET_ACCESS_KEY=FILE_STORAGE_CREDS_SECRET_ACCESS_KEY:latest,\
            WEB_SCRAPER_PROVIDER=WEB_SCRAPER_PROVIDER:latest,\
            FIRECRAWL_API_KEY=FIRECRAWL_API_KEY:latest,\
            APP_LLM_AGENT_SELECTED_LLM_MODEL_ID=APP_LLM_AGENT_SELECTED_LLM_MODEL_ID:latest,\
            APP_LLM_AGENT_SELECTED_SYSTEM_PROMPT_ID=APP_LLM_AGENT_SELECTED_SYSTEM_PROMPT_ID:latest,\
            APP_LLM_AGENT_MAX_RUNS=APP_LLM_AGENT_MAX_RUNS:latest,\
            APP_LLM_PARAMS_TEMPERATURE=APP_LLM_PARAMS_TEMPERATURE:latest,\
            APP_LLM_PARAMS_MAX_TOKENS=APP_LLM_PARAMS_MAX_TOKENS:latest,\
            APP_LLM_PARAMS_SEED=APP_LLM_PARAMS_SEED:latest,\
            APP_LLM_PARAMS_MAX_RETRIES=APP_LLM_PARAMS_MAX_RETRIES:latest,\
            APP_CHAT_INTERFACE_INITIAL_MESSAGE=APP_CHAT_INTERFACE_INITIAL_MESSAGE:latest,\
            APP_CHAT_INTERFACE_DISPLAY_NAME=APP_CHAT_INTERFACE_DISPLAY_NAME:latest,\
            APP_CHAT_INTERFACE_THEME=APP_CHAT_INTERFACE_THEME:latest,\
            APP_CHAT_INTERFACE_COLLECT_FEEDBACK=APP_CHAT_INTERFACE_COLLECT_FEEDBACK:latest,\
            APP_CHAT_INTERFACE_ALLOW_REGENERATION=APP_CHAT_INTERFACE_ALLOW_REGENERATION:latest,\
            OPENAI_API_KEY=OPENAI_API_KEY:latest,\
            PROJECT_INGESTION_SOURCE_LIMIT=PROJECT_INGESTION_SOURCE_LIMIT:latest,\
            LANGFUSE_SECRET_KEY=LANGFUSE_SECRET_KEY:latest,\
            LANGFUSE_PUBLIC_KEY=LANGFUSE_PUBLIC_KEY:latest,\
            LANGFUSE_HOST=LANGFUSE_HOST:latest,\
            QDRANT_API_KEY=QDRANT_API_KEY:latest,\
            QDRANT_INDEX_HOST=QDRANT_INDEX_HOST:latest,\
            TAVILY_API_KEY=TAVILY_API_KEY:latest,\
            APP_NOTIFICATION_BREVO_API_KEY=APP_NOTIFICATION_BREVO_API_KEY:latest,\
            APP_NOTIFICATION_BREVO_API_URL=APP_NOTIFICATION_BREVO_API_URL:latest,\
            APP_NOTIFICATION_BREVO_SENDER_EMAIL=APP_NOTIFICATION_BREVO_SENDER_EMAIL:latest,\
            APP_NOTIFICATION_BREVO_SENDER_NAME=APP_NOTIFICATION_BREVO_SENDER_NAME:latest" \
            --quiet